### ISSUE TITLE
import custom field in CSV

### ISSUE THREAD

**Issue by clvanos** [purcebr/WooCommerce-Role-Based-Coupons#1]
Hi,

Great functionality, thanks!

I want to import a lot of coupons with user role exclusion. This plugin supports custom meta fields for importing coupons:
http://docs.woothemes.com/document/customer-order-csv-import-suite/

I tried: 'meta:excluded_roles', but this is not working. Do you know how you can import the excluded roles field using a CSV?

Regards,

Clemens

**Comment by purcebr** [comment]
@clvanos Thanks for getting in touch!

This was a plugin I made a little while ago - Let me look into this - I'll let you know!

-Bryan

**Comment by purcebr** [comment]
the excluded_roles coupon meta is a serialized array of role "id" names - I'm not sure how the csv handles arrays for custom meta, like maybe if you do a comma seperated list of role id's it will automatically convert it to an array? So I can't say for sure. If you want to send me a dropbox link to the plugin, I could take a look?

**Comment by clvanos** [comment]
Hi Bryan,

Thanks for you reaction!

I attached the plugin to import coupons with support for custom meta fields.

I hope you can find the way to import the serialized array with use of the
csv.

Kind regards,

Clemens

**Comment by purcebr** [comment]
Clemens, not sure the attachment made it through - can you email it to purcebr@gmail.com?

thanks!

**Comment by purcebr** [comment]
Clemens - it doesn't look like this functionality is currently supported by the csv plugin. I should be able to push an update that will let you load a comma seperated list of role slugs in the excel upload. I'll let you know when it's ready to check out.

**Comment by purcebr** [comment]
Clemens - I pushed an update. It's untested, but it should do the trick. You'll need to enter the roles as"

`<role slug>,<role slug>,.....`

the role slug is usually just a lower-case version of the role name, with underscores instead of spaces.

Does that make sense from your end?

**Comment by clvanos** [comment]
Hi Bryan,

Thanks for the update! I tried different variations, but the excluded roles are not imported. Can you please test it?

I tried meta:excluded_roles for the column header and <administrator> as value.

**Comment by clvanos** [comment]
Hi Bryan,

I tested some cases, but the csv import won't work with your new version.
The import suite recognises the custom field, but it won't show up at the
coupon settings. Any ideas how to fix?

Regards,

Clemens

**Comment by purcebr** [comment]
@clvanos - Ok - I see what might have been the issue. The Roles were most likely working, but they weren't showing on the edit Coupon section of the backend. Can you please try the latest here? (I just pushed the update)

thanks!
